sudo: false

language: d

os:
 - linux
 - osx
 
d:
 - dmd-2.068.0
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1
 - gdc
 
matrix:
  allow_failures:
   - os: osx
     d: gdc
   - env: ARCH=x86
     d: gdc

addons:
  apt:
    packages:
     - gcc-multilib

notifications:
  email: false

env:
  global:
    - secure: "Xa3ZSmQPQytDFrMBMdhO0ObnrIb0GdvUsz0LEKxHerQN/+qSos5In5WI7ATddJyCxK1RvvzaxWdiMRurfQSSW5vAW0KCRpXnEIZ1q70+WGgXH7eOT5ZVt0bHo3L2Jo9kYXwCSWxEfiQsREliEj5RXyD4SCbGFbeP2a/4x9A1VuI="
  matrix:
    - ARCH=x86
    - ARCH=x86_64

script:
  - if [ $DC == ldc2 ] && [ $ARCH == x86_64 ];
    then
      dub test;
    else
      dub test --arch=$ARCH;
    fi

after_success:
  - ./push-ddoc.sh
